### ISSUE TITLE
Extension not populating stocks

### ISSUE THREAD

**Issue by jdamata** [cinatic/stocks-extension#1]
OS: fedora29
gnome shell:  gnome-shell-3.30.2-1.fc29.x86_64

Installed via extensions.gnome.org.

![screenshot from 2018-11-23 23-39-09](https://user-images.githubusercontent.com/33775101/48964594-0643fb80-ef79-11e8-8051-52bc8eb1bb3c.png)

**Comment by cinatic** [comment]
Hi 

Thanks for the report, unfortunately it turned out that the source (Google stocks) is blocking the request made by this extension and It's difficult to find another reliable source. But I am still looking for it from time to time in hope I can replace the underlying source api

**Comment by Liu-Kai-1991** [comment]
How about Yahoo finance?

**Comment by fh-cy** [comment]
@Liu-Kai-1991 :+1: for some (stupid) reason i skipped looking into yahoo finance because lot of ppl said it was dead. i am going to release a new version soon

**Comment by cinatic** [comment]
@Liu-Kai-1991 +1 for some (stupid) reason i skipped looking into yahoo finance because lot of ppl said it was dead. i am going to release a new version soon

**Comment by Liu-Kai-1991** [comment]
Thanks!
