### ISSUE TITLE
2024-11-13 Yahoo Reports Unauthorized and null results

### ISSUE THREAD

**Issue by brent80** [cinatic/stocks-extension#113]
Was working this morning, then stopped.  Did the yahoo api change?

**Comment by mictrik** [comment]
Same issue here.  Not sure about API but a minor update was done on Ubuntu  24.04.1 LTS today.  I did not see if it was working before update or not so i am moving cautiously and hoping a more talented person can remedy before I dive in.

**Comment by eddelbuettel** [comment]
FWIW same version works for me on (frequently suspended but currently 'awake') laptop but not on longer-running desktop.  I run another yahoo accessor I cache in Redis, and it also 'hit a wall' yesterday that was fixed by a restart.

**Comment by brent80** [comment]
More context
Ubuntu 24.04.1 LTS
GNOME Shell 46.0

**Comment by brent80** [comment]
I don't know, i just keep messing with it.  I deleted all the stocks out.  Then just added one and it started working.  I'm not sure how.  But added everything back and it seems fine.

**Comment by mictrik** [comment]
working again for me...

**Comment by eddelbuettel** [comment]
Same here.  While I did log out and in, and reinstalled to no avail at that moment ... it self-corrected overnight.

**Comment by mictrik** [comment]
Out again here 17:30 EST.   "Unkown error- Edge: too many requests"    17:32 it's back then it's out and back again.  Maybe hitting a request threshold or threshold max changed.  ??  Out again.

**Comment by eddelbuettel** [comment]
Fine here (Central time).

**Comment by mictrik** [comment]
> Fine here (Central time).

That's interesting guessing regional servers??  I have made no changes...  Still out.

**Comment by mictrik** [comment]
Up and working as of 11:06 EST.

**Comment by eddelbuettel** [comment]
Can confirm that on a laptop that I only fire up every few days it was stale again but that the tip [from this comment above](https://github.com/cinatic/stocks-extension/issues/113#issuecomment-2475998727) reset things:

```sh
dconf reset /org/gnome/shell/extensions/stocks/yahoo-meta
```
