### ISSUE TITLE
Extension too wide for the panel

### ISSUE THREAD

**Issue by herve-ma** [cinatic/stocks-extension#18]
I'd love to have the stock name and the price on the same line. Right now the extension uses two lines and it doesn't look gret (see screenshot attached). Fedora 33, Gnome shell 3.38.2
![Screenshot from 2020-12-12 15-57-43](https://user-images.githubusercontent.com/13422989/101999552-1b407400-3c93-11eb-8a52-af8b5af10380.png)

**Comment by cinatic** [comment]
I changed the base ticker font-size however this depends on the font & theme, it is also possible to customize it in the stylesheet directly
https://github.com/cinatic/stocks-extension/blob/72eb13f3b7b1e64f2d0d6e942500abbb7ee766a9/stocks%40infinicode.de/stylesheet.css#L43
