### ISSUE TITLE
is there a config file for this extension?

### ISSUE THREAD

**Issue by fgrillo** [cinatic/stocks-extension#19]
Hello, thanks for this wonderful extension! 

Is there a config file where I could add all the symbols I want to track at once instead of using the UI settings?

thank you!

**Comment by fh-cy** [comment]
you could change it with dconf editor, changes of the settings will trigger automatically a refresh

![Screenshot from 2020-12-28 13-42-31](https://user-images.githubusercontent.com/44025374/103215118-be8bbd00-4912-11eb-9a06-355d635127e6.png)

**Comment by cinatic** [comment]
you could change it with dconf editor, changes of the settings will trigger automatically a refresh

![Screenshot from 2020-12-28 13-42-31](https://user-images.githubusercontent.com/44025374/103215118-be8bbd00-4912-11eb-9a06-355d635127e6.png)

**Comment by fgrillo** [comment]
Thanks a lot!

For future reference and others with the same question, the value is base64 encoded.
