### ISSUE TITLE
SyntaxError: missing : after property id

### ISSUE THREAD

**Issue by Liu-Kai-1991** [cinatic/stocks-extension#2]
SyntaxError: missing : after property id

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1

**Comment by Liu-Kai-1991** [comment]
I am using this commit: 
https://github.com/cinatic/stocks-extension/commit/d85207787ed8a96f2e146349689fa97cac83beb2

**Comment by cinatic** [comment]
please try it  again with the latest version
