### ISSUE TITLE
Option to display multiple stocks at the same time

### ISSUE THREAD

**Issue by JacobCZ** [cinatic/stocks-extension#20]
My panel has a lot of free space to fill... It would be nice to have the option to display multiple stocks next to each other.

**Simple Solution:** Add the option to display all my stocks at the same time next to each other.

**Complicated solution:** Add the option to display *n* stocks at a time and cycle through all my stocks like normal.

Could you implement at-least one of these please?

**Comment by eddelbuettel** [comment]
I would love that too, and possibly the ability to shorten what is displayed.  I.e. tickers are often just a handful of characters, but having "level (change, pctchange)" below is -- while being a great default -- using space we could use by aligning two or more symbols.
