### ISSUE TITLE
error to enable(to load from boot) extension

### ISSUE THREAD

**Issue by maker325** [cinatic/stocks-extension#28]
Been using the extension for a couple of days and I really liked it. But today there was a sudden error. Reinstallation doesn't help in any way.
Ubuntu 20.04.2 LTS  64-bit
Gnome v.3.36.8
there are all logs that I can find in my system::
```
`11:49:26 gjs: JS WARNING: [/home/martin/.local/share/gnome-shell/extensions/stocks@infinicode.de/prefs.js 401]: reference to undefined property "active"
11:49:26 gjs: JS WARNING: [/home/martin/.local/share/gnome-shell/extensions/stocks@infinicode.de/prefs.js 401]: reference to undefined property "active"
11:49:26 gjs: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
(Note that array.toString() may have been called implicitly.)
0 decodeBase64JsonOrDefault() ["/home/martin/.local/share/gnome-shell/extensions/stocks@infinicode.de/helpers/data.js":14:23]
1 get symbolPairs() ["/home/martin/.local/share/gnome-shell/extensions/stocks@infinicode.de/prefs.js":73:23]
2 refreshUI() ["/home/martin/.local/share/gnome-shell/extensions/stocks@infinicode.de/prefs.js":411:23]
3 evaluateValues() ["/home/martin/.local/share/gnome-shell/extensions/stocks@infinicode.de/prefs.js":396:9]
4 _init() `["/home/martin/.local/share/gnome-shell/extensions/stocks@infinicode.de/prefs.js":146:9]`
5 buildPrefsWidget() ["/home/martin/.local/share/gnome-shell/extensions/stocks@infinicode.de/prefs.js":556:15]
6 _init() ["resource:///org/gnome/Shell/Extensions/js/extensionsService.js":207:39]
7 OpenExtensionPrefsAsync/<() ["resource:///org/gnome/Shell/Extensions/js/extensionsService.js":122:27]
8 asyncCallback() ["resource:///org/gnome/gjs/modules/core/overrides/Gio.js":132:12]
9 run() ["resource:///org/gnome/Shell/Extensions/js/dbusService.js":175:19]
10 main() ["resource:///org/gnome/Shell/Extensions/js/main.js":19:12]
11 run() ["resource:///org/gnome/gjs/modules/script/package.js":222:18]
12 start() ["resource:///org/gnome/gjs/modules/script/package.js":206:4]
13 <TOP LEVEL> ["/usr/share/gnome-shell/org.gnome.Shell.Extensions":1:16]

11:49:26 dbus-daemon: [session uid=1000 pid=1234] Activating service name='org.gnome.Shell.Extensions' requested by ':1.129' (uid=1000 pid=4352 comm="gnome-extensions prefs stocks@infinicode.de " label="unconfined")
11:46:41 gnome-shell: JS ERROR: Extension stocks@infinicode.de: SyntaxError: expected expression, got '.' @ /home/martin/.local/share/gnome-shell/extensions/stocks@infinicode.de/helpers/fetch.js:21`
```

**Comment by cinatic** [comment]
Hi @maker325,

thanks for the report.

From the stacktrace it looks like this is not the recent version as https://github.com/cinatic/stocks-extension/blob/master/stocks%40infinicode.de/helpers/fetch.js#L21 is currently not used in yahoo service, however it is a bug in fetching the data.

could you give me output of following commands please:
`dconf read /org/gnome/shell/extensions/stocks/symbol-pairs`
`cat ~/.local/share/gnome-shell/extensions/stocks@infinicode.de/helpers/fetch.js`
`cat ~/.local/share/gnome-shell/extensions/stocks@infinicode.de/metadata.json`

**Comment by maker325** [comment]
> Hi @maker325,
> 
> thanks for the report.
> 
> From the stacktrace it looks like this is not the recent version as https://github.com/cinatic/stocks-extension/blob/master/stocks%40infinicode.de/helpers/fetch.js#L21 is currently not used in yahoo service, however it is a bug in fetching the data.
> 
> could you give me output of following commands please:
> `dconf read /org/gnome/shell/extensions/stocks/symbol-pairs`
> `cat ~/.local/share/gnome-shell/extensions/stocks@infinicode.de/helpers/fetch.js`
> `cat ~/.local/share/gnome-shell/extensions/stocks@infinicode.de/metadata.json`

Hi there =)
here the output that you want:
`martin@martin-System:~$ dconf read /org/gnome/shell/extensions/stocks/symbol-pairs
'W3sibmFtZSI6InZpcmdpbiIsInN5bWJvbCI6IlNQQ0UiLCJzaG93SW5UaWNrZXIiOnRydWV9LHsibmFtZSI6IkJlZCBCYXRoIiwic3ltYm9sIjoiQkJCWSIsInNob3dJblRpY2tlciI6ZmFsc2V9LHsibmFtZSI6IlF1YWxjb20iLCJzeW1ib2wiOiJxY29tIiwic2hvd0luVGlja2VyIjp0cnVlfSx7Im5hbWUiOiJUU01DIiwic3ltYm9sIjoidHNtIiwic2hvd0luVGlja2VyIjp0cnVlfSx7Im5hbWUiOiJOb2tpYSIsInN5bWJvbCI6Im5vayIsInNob3dJblRpY2tlciI6ZmFsc2V9LHsibmFtZSI6ImVoZWFsdGgiLCJzeW1ib2wiOiJlaHRoIiwic2hvd0luVGlja2VyIjpmYWxzZX0seyJuYW1lIjoiTW9kZXJuYSIsInN5bWJvbCI6Im1ybmEiLCJzaG93SW5UaWNrZXIiOmZhbHNlfV0='
martin@martin-System:~$ cat ~/.local/share/gnome-shell/extensions/stocks@infinicode.de/helpers/fetch.js
const Soup = imports.gi.Soup

const DEFAULT_TIME_OUT_IN_SECONDS = 10
const DEFAULT_CHROME_USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'

const Response = class {
  constructor (message) {
    this.message = message

    if (message) {
      this.headers = message.response_headers
      this.url = message.get_uri().to_string(false)
      this.status = message.status_code
      this.statusText = Soup.Status.get_phrase(this.status)

      this.ok = (this.status === Soup.Status.OK)
    }
  }

  blob () {
    return this.message?.response_body?.data
  }

  text () {
    return this.message.response_body?.data?.toString()
  }

  json () {
    try {
      return JSON.parse(this.text())
    } catch (e) {
      return null
    }
  }
}

const appendHeaders = (message, headers) => {
  const headerNames = Object.keys(headers)
  headerNames.forEach(headerName => message.request_headers.append(headerName, headers[headerName]))
}

const generateQueryString = params => {
  if (!params) {
    return ''
  }

  // filter items without value & create pair list of paramName=paramValue
  const paramKeyValues = Object.keys(params).filter(paramName => params[paramName]).map(paramName => {
    let paramValue = params[paramName]

    if (typeof paramValue === 'boolean') {
      paramValue = paramValue ? 1 : 0
    }

    return `${paramName}=${paramValue}`
  })

  return `?${paramKeyValues.join('&')}`
}

var fetch = ({ url, method = 'GET', headers, queryParameters }) => {
  return new Promise(resolve => {
    url = url + generateQueryString(queryParameters)

    const request_message = Soup.Message.new(method, url)

    if (headers) {
      appendHeaders(request_message, headers)
    }

    const httpSession = new Soup.SessionAsync({
      user_agent: DEFAULT_CHROME_USER_AGENT,
      timeout: DEFAULT_TIME_OUT_IN_SECONDS
    })

    httpSession.queue_message(request_message, (source, response_message) => {
      const response = new Response(response_message)

      resolve(response)
    })
  })
}
martin@martin-System:~$ cat ~/.local/share/gnome-shell/extensions/stocks@infinicode.de/metadata.json
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Stocks Extension brings stock quotes to your GNOME Shell Panel",
  "localedir": "/usr/local/share/locale",
  "name": "Stocks Extension",
  "shell-version": [
    "3.34",
    "3.32",
    "3.36",
    "3.38"
  ],
  "url": "https://github.com/cinatic/stocks-extension",
  "uuid": "stocks@infinicode.de",
  "version": 14
}martin@martin-System:~$ 

`

**Comment by cinatic** [comment]
oh snap, i guess gnome shell 3.36  *gjs* does not support null safe operator. Could you try replacing the fetch.js (~/.local/share/gnome-shell/extensions/stocks@infinicode.de/helpers/fetch.js) with the following and see if it operates then normal?

```
const Soup = imports.gi.Soup

const DEFAULT_TIME_OUT_IN_SECONDS = 10
const DEFAULT_CHROME_USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'

const Response = class {
  constructor (message) {
    this.message = message

    if (message) {
      this.headers = message.response_headers
      this.url = message.get_uri().to_string(false)
      this.status = message.status_code
      this.statusText = Soup.Status.get_phrase(this.status)

      this.ok = (this.status === Soup.Status.OK)
    }
  }

  blob () {
    return ((this.message || {}).response_body || {}).data
  }

  text () {
    const data = ((this.message || {}).response_body || {}).data

    return data ? data.toString() : null
  }

  json () {
    try {
      return JSON.parse(this.text())
    } catch (e) {
      return null
    }
  }
}

const appendHeaders = (message, headers) => {
  const headerNames = Object.keys(headers)
  headerNames.forEach(headerName => message.request_headers.append(headerName, headers[headerName]))
}

const generateQueryString = params => {
  if (!params) {
    return ''
  }

  // filter items without value & create pair list of paramName=paramValue
  const paramKeyValues = Object.keys(params).filter(paramName => params[paramName]).map(paramName => {
    let paramValue = params[paramName]

    if (typeof paramValue === 'boolean') {
      paramValue = paramValue ? 1 : 0
    }

    return `${paramName}=${paramValue}`
  })

  return `?${paramKeyValues.join('&')}`
}

var fetch = ({ url, method = 'GET', headers, queryParameters }) => {
  return new Promise(resolve => {
    url = url + generateQueryString(queryParameters)

    const request_message = Soup.Message.new(method, url)

    if (headers) {
      appendHeaders(request_message, headers)
    }

    const httpSession = new Soup.SessionAsync({
      user_agent: DEFAULT_CHROME_USER_AGENT,
      timeout: DEFAULT_TIME_OUT_IN_SECONDS
    })

    httpSession.queue_message(request_message, (source, response_message) => {
      const response = new Response(response_message)

      resolve(response)
    })
  })
}
```

**Comment by maker325** [comment]
wow! its work! Thanks a lot! =)
