### ISSUE TITLE
extension config window crashes when trying to remove stock

### ISSUE THREAD

**Issue by brutog** [cinatic/stocks-extension#3]
I'm seeing the extension tweak crash on trying to remove a stock symbol. Adding and editing seemed to work fine.

Is there any information I can collect?

**Comment by cinatic** [comment]
you should get something in the logs, what system and gnome-shell version do you use?

`journalctl /usr/bin/gnome-shell`

**Comment by cinatic** [comment]
please try it with the latest version

**Comment by brutog** [comment]
Will do.

I'm using Ubuntu 18.04 with GNOME Shell 3.28.3. I didn't see anything
interesting in journalctl.

**Comment by brutog** [comment]
I re-cloned the repo and performed a make/make install. Your changes seemed to fix the issue.
