### ISSUE TITLE
Option to convert into other currency

### ISSUE THREAD

**Issue by Jurrie** [cinatic/stocks-extension#31]
My stock is displayed in Canadian dollars. I would like to view the value in euros. Could you implement an option to convert currencies?

**Comment by cinatic** [comment]
i see only one **correct** way to achieve that: fetch currency history data and correlate time with stock data. Could possibly an additional symbol field in stock settings `currency`, but honestly i am not yet really convinced having such a feature

**Comment by Jurrie** [comment]
I do not care about history data; I only would like to see the current value in euros.

However, I understand that such a feature is not at the top of the list, and hard to support if you wouldn't use it yourself :smiley:

**Comment by cinatic** [comment]
yes indeed, and what seems fine for you maybe wrong for others.. However you can also customize your local installation, just add something like:

```js
    if (['blah', 'blub'].includes(symbol)) {
      const euroConversion = 1.12
      newObject.Close = newObject.Close * euroConversion
      newObject.Low = newObject.Low * euroConversion
      newObject.High = newObject.High * euroConversion
      newObject.PreviousClose = newObject.PreviousClose * euroConversion
      newObject.PreMarketPrice = newObject.PreMarketPrice * euroConversion
      newObject.PostMarketPrice = newObject.PostMarketPrice * euroConversion
    }
```
at:
https://github.com/cinatic/stocks-extension/blob/d3cafb1fd308dbf60df0cd44b78f5942616575be/stocks%40infinicode.de/services/dto/quoteSummary.js#L94
