### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yuriw** [cinatic/stocks-extension#34]
Great app, thx !

Pls add an option to show major market indicators, e.g. NASDAQ, S&P and DOW.

**Comment by cinatic** [comment]
thanks, can you explain your idea? At the moment you already can add symbols for exchanges like ^IXIC, ^GDAXI, ^DJI, ^GSPC

**Comment by yuriw** [comment]
@cinatic That'd be enough.
However it shows wrong info in the taskbar on ubuntu 

![image](https://user-images.githubusercontent.com/3876474/111185769-90139a80-856f-11eb-830c-c12e2b3e68e8.png)

On click it seems working fine.

**Comment by cinatic** [comment]
interesting indeed. exchanges @ yahoo do not have the full name field but only a, in some circumstances not accurate, exchangeName, e.g. ^GDAXI:

```
"currency": "EUR",
"symbol": "^GDAXI",
"exchangeName": "GER",
```

thanks for the report. I will add at least a fallback to symbol when no name is provided  (#35)
In one of the next releases also the entered name when adding a symbol can be optional used (#29)
