### ISSUE TITLE
More compact display as an option?

### ISSUE THREAD

**Issue by eddelbuettel** [cinatic/stocks-extension#38]
With #20 looming around the corner (yay!) and #37 showing how to have two instances, can we make the default display of

      level (chng_in_$ | chg_in_%)

more compact?   Maybe drop one of the two changes and show just one of absolute and relative changes?   Maybe even drop level?

**Comment by cinatic** [comment]
there will be more options to configure the ticker, (#29)

**Comment by eddelbuettel** [comment]
Great to know!

(Other projects keep tickets open til feature is implemented / committed or even shipped / released but hey your project your rules.)
