### ISSUE TITLE
Red on dark gray text jarring to read

### ISSUE THREAD

**Issue by ehiggs** [cinatic/stocks-extension#4]
When a security is down it appears as literally [red](https://github.com/cinatic/stocks-extension/blob/master/stocks%40infinicode.de/stylesheet.css#L12). This is jarring to read on the dark gray background. Perhaps consider a more pastel red to make it easier to read. e.g. `#F44E3F`.

The green looks fine.

Otherwise, great little shell extension! Thanks!

**Comment by vorel41** [comment]
For me is the green too dark. Please little lighter.
Thank you for very good usefull extensiion.

**Comment by victorbadila** [comment]
A config option (either gui based or json/text) would be nice. It would also allow the extension to be theme-able.
