### ISSUE TITLE
v16 only reports that 'something is wrong'

### ISSUE THREAD

**Issue by eddelbuettel** [cinatic/stocks-extension#40]
I uninstalled completely and reinstalled from `git` via `make install`.  Trying to re-add securities gets me

![image](https://user-images.githubusercontent.com/673121/113326352-28837c00-92df-11eb-8c34-a0361407cedb.png)

Ubuntu 20.10, Unity / Gnome 3.38.  Let me know if I can help otherwise.

**Comment by cinatic** [comment]
hm could be that the scheme is not recompiled properly, can you test once again with `make mrproper buildAndReplaceLocal`

**Comment by eddelbuettel** [comment]
Done, followed by Alt-F2 r, and activation, no beans.  I do re-install from git but clean master branch.

**Comment by cinatic** [comment]
meh, it was an issue with a new introduced field inside stock items data (https://github.com/cinatic/stocks-extension/commit/9647301af4794b6006e66c2772fb85febf59abf1)

thanks for the report, testing gets more and more difficult... could you check if this version is working now with your setup?
[stocks-extension.zip](https://github.com/cinatic/stocks-extension/files/6245971/stocks-extension.zip)

**Comment by eddelbuettel** [comment]
Yay, that works!  Also love the new options, "tremendous" is a nice choice of term.

More serious, one between compact and regular would be good.  Just levels is ... not useful.  So pick change (or, better, %change -- market folks also like to talk about bp changes so 0.89% as of right now would 89bp but that is a wee bit esoteric).  Level and pct change would be good.

Next, of course, I will pester you for [Tufte-style sparklines](https://en.wikipedia.org/wiki/Sparkline) :)

**Comment by cinatic** [comment]
yes when looking now at the result only level / compact variation is probably not the best choice. At the beginning i thought to have it more customizable (enable level / perc / change) but decided to make the variations first. Maybe i remove later the compact variation and add more additional settings.

haha, actually the chart component with smaller width / height should work in the panel as well

**Comment by eddelbuettel** [comment]
Yep, not sure if you have seen a Bloomberg terminal -- super efficient use of space and "tiny" but effective sparklines next to the name.   It's been a while but I think they default to two days worth with very clever red and green.  A pipedream, but given that we are in JS now, people have done libraries for that....    But that aside what we have is pretty awesome!
