### ISSUE TITLE
Where is the config stored?

### ISSUE THREAD

**Issue by OrkanSaklan** [cinatic/stocks-extension#47]
Hey there, 

is there a way to configure the extension once with the stocks I want to show in the ticker and apply it on many different computers without starting from scratch over and over again? If yes, how? Where is the config stored?

If not, I'd like to request to add that feature.

Thanks in advance.

**Comment by cinatic** [comment]
the config is stored via dconf, check this issue how to use it: https://github.com/cinatic/stocks-extension/issues/19

**Comment by OrkanSaklan** [comment]
Thank you, that worked out for me.
