### ISSUE TITLE
Upgrade for Gnome 41

### ISSUE THREAD

**Issue by rombert** [cinatic/stocks-extension#48]
I recently updated to Gnome 41 and the extension does not load anymore. It would be great if this this could be fixed.

**Comment by nilgradisnik** [comment]
For anyone else still trying to get this extension working, clone this repo into `~/.local/share/gnome-shell/extensions/` and then compile gschema by running `glib-compile-schemas schemas/`

**Comment by eeclarkjr** [comment]
> For anyone else still trying to get this extension working, clone this repo into `~/.local/share/gnome-shell/extensions/` and then compile gschema by running `glib-compile-schemas schemas/`
> 
> Restart your GNOME shell via `Alt + F2` and type in `r`
Using Ubuntu 22.04
  Downloaded the ZIP. 
  Unzipped the file and 
  moved the stocks@infinicode.de folder to ~/.local/share/gnome-shell/extensions
  Did a reboot from the cli since Wayland won't allow the r.
