### ISSUE TITLE
Breaks in Ubuntu 19.10

### ISSUE THREAD

**Issue by reel** [cinatic/stocks-extension#5]
Does error on Ubuntu 19.10, also spits tons of error in 19.04.

Object St.Label (0x561f0ca57c70), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.

**Comment by SegFault0x0** [comment]
@cinatic Any chance on a 3.34 update soon?

**Comment by cinatic** [comment]
@SegFault0x0 
i am already on it, unfortunately the refresh icon header bar makes me some headache but i will have something next week...

**Comment by SegFault0x0** [comment]
Hey @cinatic, mind pointing out the code giving you problems?

**Comment by anarchist912** [comment]
I'd be happy to help, too. @cinatic

**Comment by herve-ma** [comment]
@cinatic any update? The ticker shows "No Data..." and the Gnome shell debugger says Unrecognized parameter "service"

**Comment by francoisjacques** [comment]
Same here. Is it still maintained?

**Comment by cinatic** [comment]
#13 partially fixed with 

proper allocating of St components will be solved in milestone v10
