### ISSUE TITLE
Where are the files installed?

### ISSUE THREAD

**Issue by AlejandroFNadal** [cinatic/stocks-extension#67]
Hi, I have a question.
The guide for installing says to move certain files to a folder, but it doesnt say from where they should be moved there, so I am a little lost now.

I am using Debian 11, I dont know if these things are installed in different places depending on the distro.

Thanks in advance

**Comment by eeclarkjr** [comment]
I am running Fedora 37 with Gnome 43. My files are stored in .local/share/gnome-shell/extensions/stocks@infinicode.de/

**Comment by cinatic** [comment]
i think it depends but in general the location is same across different linux distributions. There is a routine in the Makefile,  so in doubt you can run `make install` and it should move the files into appropriate place.

if that does not work check your distro knowledgebase or install it via EGO (https://extensions.gnome.org/extension/1422/stocks-extension/)
