### ISSUE TITLE
Error - just displays "Loading Data" in Gnome 43

### ISSUE THREAD

**Issue by eeclarkjr** [cinatic/stocks-extension#68]
Extension loads but only displays "loading data" in Gnome 43.
Suspect issue with async/await handling.

**Comment by eeclarkjr** [comment]
More details from debug mode
(gnome-shell:9174): Gjs-WARNING **: 11:00:17.494: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _sync@/home/user/.local/share/gnome-shell/extensions/stocks@infinicode.de/components/stocks/menuStockTicker.js:74:15
  _showNextStock@/home/user/.local/share/gnome-shell/extensions/stocks@infinicode.de/components/stocks/menuStockTicker.js:298:10

**Comment by eeclarkjr** [comment]
Issue might be that Soup is now 3.0 and possibly the issue lies within fetch.js

**Comment by eeclarkjr** [comment]
Is the project no longer being maintained?

**Comment by cinatic** [comment]
It is but I am currently waiting until the new gnome version is also available on my distro

**Comment by eeclarkjr** [comment]
Thanks for letting me know.  Which distro are you using?I was trying to figure out the issue but I am not familiar with SOUP2.0 or SOUP3.0. Sent from my iPhoneOn Oct 23, 2022, at 4:16 PM, Florijan Hamzic ***@***.***> wrote:﻿
It is but I am currently waiting until the new gnome version is also available on my distro

**Comment by cinatic** [comment]
fixed in https://github.com/cinatic/stocks-extension/commit/55490bcda8960c11c19ceec1ca92102e047fd791 thanks for the report
