### ISSUE TITLE
Opening settings crashes extension

### ISSUE THREAD

**Issue by shreyas-shriyan** [cinatic/stocks-extension#69]
distro: ubuntu 22.10
gnome: 43

1. clicking the settings button crashes extension with error =>  execution of gnome-shell-extension-prefs failed: command not found
2. unable to search and add any other stocks than the predefined one

**Comment by cinatic** [comment]
oh yes it's deprecated now i think, will take a while to figure out what is now the appopriate way to do this. As a workaround you can also directly save the setting via dconf:

1. Build your symbols JSON
```
[
  {
    "id": "622416f280664b6aa2c09b9b62585289",
    "name": "GGPI",
    "symbol": "GGPI",
    "provider": "yahoo",
    "showInTicker": true
  },
  {
    "id": "0b4b649a06285dbdc795ed5762585289",
    "name": "Alibaba Xetra",
    "symbol": "AHLA.DE",
    "provider": "yahoo",
    "showInTicker": true
  }
]

```
2. base64 encode this JSON and save it via dconf

```
dconf write /org/gnome/shell/extensions/stocks/symbol-pairs "'BASE_ENCODED_STR_HERE'"
```

**Comment by lhall-amphibee** [comment]
It's working, but not very user friendly :D
