### ISSUE TITLE
Attempting to change the settings throws an exception

### ISSUE THREAD

**Issue by brunkenj** [cinatic/stocks-extension#71]
This is seen on Fedora 36 with all available updates, Gnome 41.6, and version 20 of the extension. Version 20 appears to be the latest version of the extension that is compatible with Gnome 41.6.

The following exception is thrown when the gear icon is selected. Gnome opens up a window with an error notification and the following text in the Technical Details box:

Error: Requiring Adw, version none: Typelib file for namespace 'Adw' (any version) not found

Stack trace:
  @/home/user/.local/share/gnome-shell/extensions/stocks@infinicode.de/components/settings/aboutPage.js:4:53
  @/home/user/.local/share/gnome-shell/extensions/stocks@infinicode.de/prefs.js:6:23
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:216:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by brunkenj** [comment]
To be clear, this is not the same type of failure as reported in issue #69.

**Comment by cinatic** [comment]
yes i mixed up the compat list in EGO, so you probably always fall back to v20 which of course will not work. Not sure actually how to fix this, please use v19 or whatever version is working with 41

**Comment by brunkenj** [comment]
Going back to v19 did solve the problem. I edited metadata.json to add "41" to the shell-version field.

Should this issue be left open?

**Comment by cinatic** [comment]
yes let's keep it open and thanks for the report
