### ISSUE TITLE
How to use eastmoney provider option

### ISSUE THREAD

**Issue by Huang-CL** [cinatic/stocks-extension#76]
Since Yahoo no longer provides service on the Chinese mainland, I have to switch to the eastmoney provider. However, I tested many symbol names and none of them worked.  Could you please provide a demo on how to use eastmoney provider?  It would be helpful to use SP 500 index and CSI 300 Index as examples. Thanks!  @wangshouren000

**Comment by cinatic** [comment]
Their identifers have two parts, i can not tell you for sure what they stand for, it seems the first one is the stock and the latter the exchange, however just watch the urls on there site and try it out, i will add a note in the readme:

![Screenshot from 2023-02-01 10-19-15](https://user-images.githubusercontent.com/2721787/216002869-d5a23521-1228-4147-a7cf-badae244d047.png)

**Comment by Huang-CL** [comment]
Thanks!
The symbol 1.000001 (second in your list) tracks the SSE Composite Index. Could you let me know where you locate these identifiers? The webpage for the SSE Composite Index is http://quote.eastmoney.com/zs000001.html.  There is no way for me to figure out the symbol from this url.

**Comment by Huang-CL** [comment]
I have figured this out. 
When hovering the cursor over the SSE Composite Index, the link that appears is http://quote.eastmoney.com/unify/r/1.000300.   This is the identifier needed.  
After clicking the link, the website will auto-direct to http://quote.eastmoney.com/zs000001.html.  This is not the identifier that feeds the extension.
