### ISSUE TITLE
GLib.FileError: Failed to open file “/home/user/.local/share/gnome-shell/extensions/stocks@infinicode.de/schemas/gschemas.compiled”: open() failed: No such file or directory

### ISSUE THREAD

**Issue by eeclarkjr** [cinatic/stocks-extension#83]
GLib.FileError: Failed to open file “/home/user/.local/share/gnome-shell/extensions/stocks@infinicode.de/schemas/gschemas.compiled”: open() failed: No such file or directory

**Comment by cinatic** [comment]
that was fast, schema xml was missing in the package, fixed in 11b3df1
