### ISSUE TITLE
json SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data.

### ISSUE THREAD

**Issue by stejp96** [cinatic/stocks-extension#86]
Hi, I'm getting this error for each time it refreshes the stocks. It doesn't seem to have any impact on usability, so it might be nothing.

The entire log:
`gnome-shell[41994]: failed to decode base64 json SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
`

**Comment by translucide** [comment]
Fixed in https://github.com/cinatic/stocks-extension/commit/e1a77b92f90c7197f0e896b0e448f270365aa67f

Let's see if this gets merged...
