### ISSUE TITLE
v24.1 doesn't have the yahoo backport

### ISSUE THREAD

**Issue by BirdOfChaos** [cinatic/stocks-extension#94]
There is a problem with the tag v24.1. If I'm not mistaken, it's supposed to include the changes from [v24_fixed_yahoo_api](https://github.com/cinatic/stocks-extension/tree/v24_fixed_yahoo_api), but it doesn't. It looks like the tag v24.1 was made from v20.

See https://github.com/cinatic/stocks-extension/pull/91#issuecomment-1777987928

**Comment by cinatic** [comment]
thanks yes sth went wrong, now v24.1 & the release contains the right things

**Comment by BirdOfChaos** [comment]
That was super quick. Thank you very much!

**Comment by chrismonks** [comment]
still not working for me :(
