### ISSUE TITLE
Raw HTML as output

### ISSUE THREAD

**Issue by D4T4R** [cinatic/stocks-extension#95]
Extension started spitting out raw html instead of formatted text after the stock name for Gnome 44. Cannot use the gnome 45 version as I am using PopOS.

**Comment by z369369** [comment]
I have the same issue.  I use GNOME 43.6 in Debian 12.

**Comment by D4T4R** [comment]
@cinatic need help here

**Comment by D4T4R** [comment]
Thanks !

**Comment by D4T4R** [comment]
@cinatic  any way this can be done?

**Comment by cinatic** [comment]
i prepared packages for older gnome-shell versions, let me know if it works for you

https://github.com/cinatic/stocks-extension/releases/tag/v24.2-GS42
https://github.com/cinatic/stocks-extension/releases/tag/v32-GS43_44

**Comment by diegogen** [comment]
Worked ok for me in gnome 42.9 on ubuntu 22.04, thank you!

**Comment by D4T4R** [comment]
> i prepared packages for older gnome-shell versions, let me know if it works for you
> 
> https://github.com/cinatic/stocks-extension/releases/tag/v24.2-GS42 https://github.com/cinatic/stocks-extension/releases/tag/v32-GS43_44

Worked for me (42.5) Thank you ! This extension has become a daily requirement for me now

**Comment by ttabi** [comment]
I tried https://github.com/cinatic/stocks-extension/releases/tag/v24.2-GS42 on Ubuntu 22 (Gnome 42.9) and the Yahoo ticker doesn't work.

![image](https://github.com/cinatic/stocks-extension/assets/59890156/74e12639-c7d0-4ca1-bf65-f5274adca56c)
